name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: release
      uses: ./.github/actions/github-release
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

