name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-lastest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: upload zip
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload tar.gz
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: gz
        GHR_PATH: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
