name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: release
      uses: .github/actions/github-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Runs a single command using the runners shell
#    - name: Run a one-line script
#      run: echo Hello, world!

